openapi: 3.0.0

info:
  title: PizzaMeow API
  version: 0.0.0
  description: Предоставляет доступ к базовым ресурсам сервера
  
servers:
  - url: /api


# Пути, которые поддерживает API
paths:
  # ВСЕ ПУТИ СВЯЗАННЫЕ
  # С ТАБЛИЦЕЙ USER
  /users/signup:
    post:
      summary: Зарегистрировать нового пользователя по регистрационным данным (email, password) и вернуть токен доступа для зарегистрированного аккаунта
      operationId: server.app.views.users.sign_up
      requestBody:
        description: Регистрационные данные
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UserSignUp'
      responses:
        '200':
          description: Новый пользователь успешно зарегистрирован
          content:
            'text/plain':
              schema:
                $ref: '#/components/schemas/Token'
        
  /users/signin:
    get:
      summary: Получить токен по регистрационным данным (email, password)
      operationId: server.app.views.users.sign_in
      parameters:
        - name: email
          description: Почта, указанная при регистрации аккаунта
          required: true
          in: query
          schema:
            type: string
        - name: password
          description: Пароль от аккаунта
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'text/plain':
              schema:
                type: string
                
  /users/config/update:
    patch:
      summary: Частично обновляет данные о пользователе
      operationId: server.app.views.users.update_config
      requestBody:
        description: Данные о пользователе
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UserConfig'
      responses:
        '204':
          description: Данные успешно обновлены
      security:
      - jwt: []
    
  /users/change_password:
    put:
      summary: Изменяет пароль от учётной записи
      operationId: server.app.views.users.change_password
      requestBody:
        description: Новый пароль
        required: true
        content:
          'text/plain':
            schema:
              type: string
      responses:
        '204':
          description: Пароль успешно обновлён
      security:
      - jwt: []

  /users/reset_password:
    put:
      summary: Сбрасывает пароль, отправляет новый пароль на почту
      operationId: server.app.views.users.reset_password
      requestBody:
        description: Почта пользователя
        required: true
        content:
          'text/plain':
            schema:
              type: string
      responses:
        '204':
          description: Новый пароль был отправлен на вашу почту.

  /users/change_email:
    put:
      summary: Изменяет почту учётной записи
      operationId: server.app.views.users.change_email
      requestBody:
        description: Новая почта
        required: true
        content:
          'text/plain':
            schema:
              type: string
      responses:
        '204':
          description: Почта успешно обновлена
      security:
      - jwt: []

  /users/confirm/send:
    get:
      summary: Получить письмо, с ссылкой на подтверждение аккаунта
      operationId: server.app.views.users.send_confirm_email
      parameters:
        - name: email
          description: Адрес почты, на который нужно отправить письмо 
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
      security:
      - jwt: []
  /users/confirm:
    get:
      summary: Подтверждает акканут пользователя
      operationId: server.app.views.users.confirm_email
      parameters:
        - name: email_confirmation_token
          description: Токен подтверждения аккаунта
          in: query
          schema:
            type: string
      responses:
        '204':
          description: Данные успешно обновлены


  # ВСЕ ПУТИ, СВЯЗАННЫЕ
  # С ТАБЛИЦЕЙ PIZZA
  /pizzas:
    get:
      summary: Получить список всех пицц
      operationId: server.app.views.pizzas.get_pizzas_page
      parameters:
        - name: offset
          description: Число элементов, которые нужно пропустить от начала таблицы перед началом сборки итогового списка
          in: query
          schema:
            type: integer
            minimum: 0
        - name: limit
          description: Максимальное число элементов, которое будет в списке. Сервер будет пытаться заполнить список ровно таким числом элементов.
          in: query
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'




# КОМПОНЕНТЫ ЗАПРОСОВ
components:
  # Схемы параметров запроса или ответа
  schemas:
    # Схема данных о пицце
    Pizza:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный ID пиццы
        name:
          type: string
          description: Название пиццы
        description:
          type: string
          description: Описание пиццы
      required:
        - id
        - name

    # Схема регистрационных данных
    UserSignUp:
      type: object
      properties:
        email:
          type: string
          description: Электронная почта пользователя
        password:
          type: string
          description: Пароль от аккаунта пользователя
      required:
        - email
        - password
      
    # Схема данных о пользователе
    UserConfig:
      type: object
      properties:
        firstname:
          type: string
          description: Имя пользователя
        lastname:
          type: string
          description: Фамилия пользователя
        address:
          type: string
          description: Адрес пользователя
        phone:
          type: string
          description: Номер телефона пользователя

    # Схема токена
    Token:
      type: string
  
  # Универсальные ответы от сервера
  responses:
    UnauthorizedError:
      description: Попытка неавторизованного получения данных
  
  # Безопасность
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: server.app.utils.auth.decode_token