openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: My API description

servers:
 - url: /api

components:
  schemas:
    Person:
      type: object
      required:
        - lname
      properties:
        lname:
          type: string
        fname:
          type: string
  parameters:
    lname:
      name: lname
      in: path
      required: true
      schema:
        type: string

paths:
  /people:
    get:
      summary: Get list of all people
      tags:
       - people
      operationId: people.get_all_people
      responses:
        '200':
          description: Successfully read all people
    post:
      summary: Create a new person
      tags:
       - people
      operationId: people.create_person
      requestBody:
        description: Person to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Some
  /people/{lname}:
    get:
      summary: Get list of all people
      tags:
       - people
      operationId: people.get_person
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        '200':
          description: Successfully read people